#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# MONITOR SETTING
bspc monitor -d 1 2 3 4 5 6 

# BSPWM CONFIGURATION
bspc config border_width        2 
bspc config window_gap          8 
bspc config top_padding		35							
bspc config bottom_padding	2	
bspc config left_padding	2	
bspc config right_padding	2	
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle  false 
bspc config gapless_monocle     false 

# BSPWM COLORING
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#FF0000"
bspc config focused_border_color	"#FFFFFF"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

# BSPWM RULES
bspc rule -a Firefox desktop='^2' state=tiled follow=on
bspc rule -a Pcmanfm desktop='^5' state=tiled follow=on
bspc rule -a vlc desktop='^6' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## AUTO-START ##
# WALLPAPER
feh --bg-fill ~/Pictures/Wallpapers/Black_building.jpg

# STATUS BAR
polybar -r -c ~/.config/polybar/config.ini &

# COMPOSITOR
picom --config ~/.config/picom/picom.conf &

# WIDGETS
exec conky -c ~/.config/conky/Mintaka/Mintaka.conf
